name: cpplint

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master, yiguan/ci ]

jobs:
  checkstyle:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
  
      - name: Install cpplint
        run: pip3 install cpplint

      - name: Run Linter
        run: |
          cd Team11/Code11/src/spa
          cpplint --recursive --filter=-legal/copyright,-build/c++11,-runtime/references,-whitespace/indent,-build/include_what_you_use,-whitespace/comments,-readability/todo,-runtime/invalid_increment --linelength=140 extensions=cpp,h .
