name: System Tests timing

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master, yiguan/ci ]

jobs:
    build-and-test:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v3

            - name: Build project
              uses: threeal/cmake-action@v1.3.0
              with:
                source-dir: Team11/Code11
                generator: Ninja
                c-compiler: clang
                cxx-compiler: clang++
                run-build: true
                build-args: --config Release
            
            - name: Time system test
              working-directory: ${{runner.workspace}}/23s1-cp-spa-team-11/Team11/Code11
              run: |
                time ./RunAllSystemTest.sh ./build/src/autotester/autotester >> time_output.txt
            - name: Time system test
              working-directory: ${{runner.workspace}}/23s1-cp-spa-team-11/Team11/Code11
              run: |
                time ./RunAllSystemTest.sh ./build/src/autotester/autotester >> time_output.txt
            - name: Time system test
              working-directory: ${{runner.workspace}}/23s1-cp-spa-team-11/Team11/Code11
              run: |
                time ./RunAllSystemTest.sh ./build/src/autotester/autotester >> time_output.txt
            - name: Time system test
              working-directory: ${{runner.workspace}}/23s1-cp-spa-team-11/Team11/Code11
              run: |
                time ./RunAllSystemTest.sh ./build/src/autotester/autotester >> time_output.txt
            - name: Time system test
              working-directory: ${{runner.workspace}}/23s1-cp-spa-team-11/Team11/Code11
              run: |
                time ./RunAllSystemTest.sh ./build/src/autotester/autotester >> time_output.txt

            - name: Save tests output
              uses: actions/upload-artifact@v3
              with:
                name: time-output
                path: ${{runner.workspace}}/23s1-cp-spa-team-11/Team11/Code11/tests

            - name: Get output
              working-directory: ${{runner.workspace}}/23s1-cp-spa-team-11/Team11/Code11
              id: sys-time-output
              run: |
                echo "::set-output name=result::$(cat time_output.txt)"

            - name: Comment PR
              uses: thollander/actions-comment-pull-request@v2
              if: github.event_name != 'push'
              with:
                message: |
                 Autotester result: ${{ steps.sys-time-output.outputs.result }}
